create database tu_search_directory;

USE TU_SEARCH_DIRECTORY;

CREATE TABLE CENTRAL_OFFICE(
ORG_ID INT NOT NULL,
NAME VARCHAR(20),
ADDRESS VARCHAR(50),
PRIMARY KEY (ORG_ID));

CREATE TABLE INSTITUTE_FACULTIES (
    ID int NOT NULL AUTO_INCREMENT,
    ORG_ID int NOT NULL,
    NAME VARCHAR(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (ORG_ID) REFERENCES CENTRAL_OFFICE(ORG_ID)
);

ALTER TABLE INSTITUTE_FACULTIES AUTO_INCREMENT=101;

CREATE TABLE CENTRAL_DEPARTMENT (
    id INT NOT NULL AUTO_INCREMENT,
    org_id int,
    name VARCHAR(100) NOT NULL,
    head_id VARCHAR(255),
    contact VARCHAR(255),
    location VARCHAR(255),
    isActive BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (org_id) REFERENCES CENTRAL_OFFICE(org_id)
);

ALTER TABLE CENTRAL_DEPARTMENT AUTO_INCREMENT=201;

ALTER TABLE CENTRAL_DEPARTMENT DROP COLUMN HEAD_ID;

ALTER TABLE CENTRAL_DEPARTMENT ADD COLUMN website VARCHAR(255);

CREATE TABLE CAMPUS (
    id  INT NOT NULL AUTO_INCREMENT,
    ho_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    PRIMARY KEY (id), 
    FOREIGN KEY (ho_id) REFERENCES INSTITUTE_FACULTIES(id)
);
	
ALTER TABLE CAMPUS AUTO_INCREMENT=1001;

ALTER TABLE CAMPUS ADD COLUMN website VARCHAR(255);

CREATE TABLE DEPARTMENT (
    id INT NOT NULL AUTO_INCREMENT,
    c_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    contact VARCHAR(255),
    isCentral BOOLEAN,
    PRIMARY KEY (ID),
    FOREIGN KEY (c_id) REFERENCES CAMPUS(id)
);

ALTER TABLE DEPARTMENT AUTO_INCREMENT=101;

ALTER TABLE DEPARTMENT DROP COLUMN isCentral;

CREATE TABLE PERSONNEL (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    position VARCHAR(255),
    imageUrl VARCHAR(255),
    org_id INT, -- If belongs to Central Office
    faculty_id INT, -- If belongs to an Institute/Faculty
    campus_id INT, -- If belongs to a Campus
    dept_id INT, -- If belongs to a Department
    c_dept_id INT, -- If belongs to a Central Department
    PRIMARY KEY (id),
    FOREIGN KEY (org_id) REFERENCES CENTRAL_OFFICE(org_id),
    FOREIGN KEY (faculty_id) REFERENCES INSTITUTE_FACULTIES(id),
    FOREIGN KEY (campus_id) REFERENCES CAMPUS(id),
    FOREIGN KEY (dept_id) REFERENCES DEPARTMENT(id),
    FOREIGN KEY (c_dept_id) REFERENCES CENTRAL_DEPARTMENT(id)
);

ALTER TABLE PERSONNEL AUTO_INCREMENT=1000001;

CREATE TABLE PROGRAM (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    about TEXT,
    director_id INT,
    PRIMARY KEY (id),
    FOREIGN KEY (director_id) REFERENCES PERSONNEL(id)
);

ALTER TABLE PROGRAM AUTO_INCREMENT=301;